# Generated by Django 4.2.4 on 2023-08-29 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='winners',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='winners',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
        migrations.DeleteModel(
            name='Winners',
        ),
    ]
